name: CI Pipeline - Backend & Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    - name: Construir la aplicación
      run: dotnet build api/Basic3TierAPI/Basic3TierAPI.sln --configuration Release

    - name: Ejecutar pruebas API
      run: dotnet test api/Tests/Basic3TierAPI.Tests/Basic3TierAPI.Tests.csproj --no-build --verbosity normal

  docker-build-push:
    needs: build-test-backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Iniciar sesión en Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Construir y subir imagen del backend
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/basic3tier-api:latest -f api/Dockerfile api
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/basic3tier-api:latest ${{ secrets.DOCKERHUB_USERNAME }}/basic3tier-api:${{ github.run_number }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/basic3tier-api:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/basic3tier-api:${{ github.run_number }}

    - name: Construir y subir imagen del frontend
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/basic3tier-ui:latest -f ui/Dockerfile ui
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/basic3tier-ui:latest ${{ secrets.DOCKERHUB_USERNAME }}/basic3tier-ui:${{ github.run_number }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/basic3tier-ui:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/basic3tier-ui:${{ github.run_number }}
  
  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: docker-build-push

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}

    - name: Copiar docker-compose.yml a la VM
      run: |
        scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.AZURE_SSH_USERNAME }}@${{ secrets.AZURE_VM_IP }}:/home/${{ secrets.AZURE_SSH_USERNAME }}/docker-compose.yml

    - name: Conectar a la VM y ejecutar Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_SSH_USERNAME }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/basic3tier-api:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/basic3tier-ui:latest
          cd /home/${{ secrets.AZURE_SSH_USERNAME }}
          docker-compose up -d
        EOF
