name: CI Pipeline - Backend & Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    - name: Ejecutar pruebas API
      run: dotnet test api/Tests/Basic3TierAPI.Tests/Basic3TierAPI.Tests.csproj --verbosity normal

    - name: Ejecutar pruebas Infrastructure
      run: dotnet test api/Tests/Basic3Tier.Infrastructure.Tests/Basic3Tier.Infrastructure.Tests.csproj --verbosity normal

    - name: Ejecutar pruebas Core
      run: dotnet test api/Tests/Basic3Tier.Core.Tests/Basic3Tier.Core.Tests.csproj --verbosity normal

    - name: Ejecutar análisis SonarQube
      run: |
        dotnet sonarscanner begin /k:"ivsancheza-3-tier-app" /d:sonar.host.url="http://${{ secrets.AZURE_VM_IP }}:9000" /d:sonar.token="${{ secrets.SONARQUBE_TOKEN }}"
        dotnet build api/Basic3TierAPI/Basic3TierAPI.sln --configuration Release
        dotnet sonarscanner end /d:sonar.token="${{ secrets.SONARQUBE_TOKEN }}"

  docker-build-push:
    needs: build-test-backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Iniciar sesión en Docker Hub
      uses: docker/login-action@v2
      with:
        username: ivsancheza
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Construir y subir imagen del backend
      run: |
        docker build -t ivsancheza/basic3tier-api:latest -f api/Dockerfile api
        docker push ivsancheza/basic3tier-api:latest

    - name: Construir y subir imagen del frontend
      run: |
        docker build -t ivsancheza/basic3tier-ui:latest -f ui/Dockerfile ui
        docker push ivsancheza/basic3tier-ui:latest
  
  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: docker-build-push

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}

    - name: Copiar docker-compose.yml a la VM
      run: |
        scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.AZURE_SSH_USERNAME }}@${{ secrets.AZURE_VM_IP }}:/home/${{ secrets.AZURE_SSH_USERNAME }}/docker-compose.yml

    - name: Conectar a la VM y ejecutar Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_SSH_USERNAME }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
          docker pull ivsancheza/basic3tier-api:latest
          docker pull ivsancheza/basic3tier-ui:latest
          cd /home/${{ secrets.AZURE_SSH_USERNAME }}
          docker-compose down -v
          docker-compose up -d
        EOF
